<a href="https://colab.research.google.com/github/csap7/ictiitk/blob/master/ai_20062019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import urllib.request
import warnings
warnings.filterwarnings(action="ignore")

In [0]:
list1 = [1, 2, 3]
print("list1 * 4 = ", list1 * 4)

list1 * 4 =  [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [0]:
nparr = np.array([1,2,3])
print("nparr*4=", nparr*4)
print("nparr+4=", nparr+4)
print("nparr/2=", nparr/2)
print("nparr/2.0=", nparr/2)
print("nparr//2.0=", nparr//2.0)
print("nparr//2=", nparr//2)
print(type(nparr), nparr.dtype, nparr.size)

nparr*4= [ 4  8 12]
nparr+4= [5 6 7]
nparr/2= [0.5 1.  1.5]
nparr/2.0= [0.5 1.  1.5]
nparr//2.0= [0. 1. 1.]
nparr//2= [0 1 1]
<class 'numpy.ndarray'> int64 3


In [0]:
ddarr= np.array([[1,2,3],[4,5,6]])
print(ddarr.ndim, ddarr.shape, ddarr.size, ddarr.dtype)
print(ddarr[0,1])
print(ddarr[0])
print(ddarr[:,0])
print(ddarr[1,:])

2 (2, 3) 6 int64
2
[1 2 3]
[1 4]
[4 5 6]


In [0]:
d1= np.array([[1,2],
              [3,4],
              [5,6],
              [7,8],
              [9,10],
              [11,12],
              [13,14]])
print(d1, d1.shape, d1.ndim)
print(d1[: :2,0])
print(d1[: :2])
print(d1[1: :2, 1])
print(d1[1: :3, 0])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]] (7, 2) 2
[ 1  5  9 13]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[ 4  8 12]
[3 9]


In [0]:
zr=np.zeros([3,4])
print(zr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
ar=np.ones([4,4])
print(ar*4)
print(ar)
print(ar.dtype)

[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64


In [0]:
ar=np.arange(1,6)
print(ar)

[1 2 3 4 5]


In [0]:
ar[3]=16
print(ar)

[ 1  2  3 16  5]


In [0]:
arr= np.array([11, 22, 33, 0. , 44, 55])
print(arr.sum())
print(arr.std())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.size)

print(arr.nonzero())
print(arr.dtype)

165.0
18.786076404259266
27.5
55.0
0.0
6
(array([0, 1, 2, 4, 5]),)
float64


In [0]:
print(np.all([1,2,3,4]))
print(np.all([1,2,0,3,4]))
print(np.any([1,2,3,4]))
print(np.any([1,2,0,3,4]))

True
False
True
True


In [0]:
n1=np.array([4,5,6])
n2=np.array([1,2,3])
print(n1)
print(n2)
print(n1+n2)
print(n1-n2)

n3=np.array([4,5,6,7])
print(n1+n3)

[4 5 6]
[1 2 3]
[5 7 9]
[3 3 3]


ValueError: ignored

In [0]:
n4=np.array([10, -1, 0,90,300,3,-6,2])
print(n4)
#n4.sort()
#print(n4)
print(n4.argsort())
for i in n4.argsort():
  print(n4[i], end=" ")

[ 10  -1   0  90 300   3  -6   2]
[ -6  -1   0   2   3  10  90 300]
[0 1 2 3 4 5 6 7]
-6 -1 0 2 3 10 90 300 